<#
.SYNOPSIS
    ランチャー向けの配信サーバー（IIS）を初回構築する。何度実行しても同じ状態になる。

.DESCRIPTION
    1. IIS（Windows標準のWebサーバー機能）を入れる
    2. 公開フォルダ（既定: C:\simutrans-dist）を作り、指定ポート（既定: 8080）で公開するサイトを作る
    3. Windowsファイアウォールでそのポートを開ける
    4. 読み出し（GET / HEAD）以外の要求を断る設定を入れる
    5. サーバーリスト（新しく作るときは list-ランダム.json）がなければ、1台目のサーバーを登録してpaksetを公開する（Add-Server.ps1）
       あれば、登録済みのpaksetを公開し直す（Publish-Pakset.ps1）
    6. サーバーリストに署名する（署名の鍵がなければ作る。Signing.ps1を参照）
    7. サーバーリストを取得できること、書き込み要求が断られることを確かめ、友人に伝えるアドレスと確認コードを表示する

    足りない情報は実行中に質問するので、引数なしで実行してもよい。
    管理者として実行すること（Setup-Server.batをダブルクリックすると管理者として起動する）。

.EXAMPLE
    .\Install-DistServer.ps1 -PublicHost example.ddns.net -ServerName "友達内輪鯖A" `
        -PaksetSource C:\simutrans-server\pak128.japan
#>
[CmdletBinding()]
param(
    # 配信に使うポート
    [int] $Port = 8080,
    # 公開フォルダ
    [string] $DistDir = 'C:\simutrans-dist',
    # IISのサイト名
    [string] $SiteName = 'simutrans-dist',
    # 友人が接続に使うドメイン（例: example.ddns.net）
    [string] $PublicHost,
    # サーバーリストに書くサーバー名
    [string] $ServerName,
    # サーバーリストに書くサーバーのid（省略すると自動で決める）
    [string] $ServerId,
    # simutransサーバーのポート（省略すると質問する）
    [int] $GamePort,
    # simutransサーバーが使っているpaksetフォルダのフルパス（省略すると質問する）
    [string] $PaksetSource,
    # HTTPSのポート
    [int] $HttpsPort = 8443,
    # HTTPSにしない（署名があるので本体も配れるが、通信の中身は暗号化されない）
    [switch] $SkipHttps,
    # 証明書の期限切れなどの連絡先（任意）
    [string] $Email
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Common.ps1')
$RootWebConfigMarker = 'Generated by Install-DistServer.ps1'

# --- 0. 確認---
$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw '管理者として実行してください（Setup-Server.batをダブルクリックすると管理者として起動します）'
}
if ($Port -lt 1 -or $Port -gt 65535) { throw "ポート番号が正しくありません: $Port" }

# --- 1. IIS ---
Write-Step 'IIS（Webサーバー機能）を確認しています'
if (Get-Command Install-WindowsFeature -ErrorAction SilentlyContinue) {
    # Windows Server
    $result = Install-WindowsFeature Web-Server, Web-Static-Content -IncludeManagementTools
    if ($result.RestartNeeded -eq 'Yes') {
        Write-Warning 'IISを使うにはWindowsの再起動が必要です。再起動してから、もう一度このスクリプトを実行してください'
        return
    }
}
else {
    # Windows 10 / 11
    $result = Enable-WindowsOptionalFeature -Online -All -NoRestart -FeatureName IIS-WebServerRole, IIS-WebServer, IIS-StaticContent, IIS-ManagementConsole
    if ($result.RestartNeeded) {
        Write-Warning 'IISを使うにはWindowsの再起動が必要です。再起動してから、もう一度このスクリプトを実行してください'
        return
    }
}
Import-Module WebAdministration
Write-Ok 'IISが使えます'

# --- 2. 公開フォルダとサイト---
Write-Step "公開フォルダ $DistDir をポート $Port で公開します"
New-Item -ItemType Directory -Force -Path $DistDir | Out-Null

$conflict = @(Get-WebBinding | Where-Object {
    $_.protocol -eq 'http' -and ($_.bindingInformation -split ':')[1] -eq "$Port" -and
    $_.ItemXPath -notmatch "@name='$([regex]::Escape($SiteName))'"
})
if ($conflict.Count -gt 0) {
    throw "ポート $Port はIISの別のサイトが使っています。-Portで別の番号を指定してください"
}

if (Get-Website -Name $SiteName) {
    Set-ItemProperty "IIS:\Sites\$SiteName" -Name physicalPath -Value $DistDir
    Get-WebBinding -Name $SiteName | Remove-WebBinding
    New-WebBinding -Name $SiteName -Protocol http -Port $Port -IPAddress '*'
}
else {
    New-Website -Name $SiteName -PhysicalPath $DistDir -Port $Port | Out-Null
}
# フォルダの中身の一覧表示は明示的にオフにする
Set-WebConfigurationProperty -PSPath "IIS:\Sites\$SiteName" -Filter /system.webServer/directoryBrowse -Name enabled -Value $false

# 読み出し（GET / HEAD）以外の要求は断る。公開フォルダ直下のweb.configに書く（自分で作ったものがあれば触らない）
$rootWebConfig = Join-Path $DistDir 'web.config'
if (-not (Test-Path -LiteralPath $rootWebConfig) -or (Get-Content -LiteralPath $rootWebConfig -Raw).Contains($RootWebConfigMarker)) {
    Write-TextFile $rootWebConfig @"
<?xml version="1.0" encoding="utf-8"?>
<!-- $RootWebConfigMarker. 読み出し（GET / HEAD）以外の要求を断る。-->
<configuration>
  <system.webServer>
    <security>
      <requestFiltering>
        <verbs allowUnlisted="false">
          <add verb="GET" allowed="true" />
          <add verb="HEAD" allowed="true" />
        </verbs>
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
"@
}
Start-Website -Name $SiteName
Write-Ok "サイト $SiteName をポート $Port で公開しました（読み出し以外の要求は断る設定）"

# --- 3. ファイアウォール---
Write-Step "Windowsファイアウォールでポート $Port を開けます"
$ruleName = "simutrans-dist (TCP $Port)"
if (-not (Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue)) {
    New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Protocol TCP -LocalPort $Port -Action Allow | Out-Null
}
Write-Ok "ルール「$ruleName」があります"

# --- 4. サーバーの登録とpaksetの公開---
$manifestPath = Resolve-ManifestPath $DistDir
$servers = @(if (Test-Path -LiteralPath $manifestPath) { (Read-JsonFile $manifestPath).servers })
if ($servers.Count -eq 0) {
    # 1台目のサーバーを登録する（足りない情報はAdd-Server.ps1が質問する）
    $addArgs = @{ DistDir = $DistDir }
    foreach ($name in @('ServerName', 'ServerId', 'PublicHost', 'GamePort', 'PaksetSource')) {
        $value = Get-Variable -Name $name -ValueOnly
        if ($value) { $addArgs[$name] = $value }
    }
    & (Join-Path $PSScriptRoot 'Add-Server.ps1') @addArgs
    $servers = @((Read-JsonFile $manifestPath).servers)
    if (-not $PublicHost) { $PublicHost = ($servers[0].address -split ':')[0] }
}
else {
    Write-Step "サーバーリスト（$(Split-Path -Leaf $manifestPath)）を確認しています"
    Write-Ok "既存のサーバーリストをそのまま使います（$($servers.Count)台）"
    if (-not $PublicHost) { $PublicHost = ($servers[0].address -split ':')[0] }

    # 公開の登録がないサーバー（以前の版で構築した場合など）は、paksetフォルダを聞いて登録する
    $settings = Get-PublishSettings
    $settings.manifest = $manifestPath
    $registered = @($settings.paksets | ForEach-Object { $_.server_ids })
    foreach ($server in $servers) {
        if ($registered -contains $server.id) { continue }
        $source = $PaksetSource
        while (-not $source) {
            $answer = (Read-Host "サーバー「$($server.name)」が使っているpaksetフォルダのフルパス（空欄なら今回は公開しない）").Trim().Trim('"')
            if (-not $answer) { break }
            if (Test-Path -LiteralPath $answer -PathType Container) { $source = $answer }
            else { Write-Warning "フォルダが見つかりません: $answer" }
        }
        if ($source) {
            Add-PublishEntry $settings (Get-FullPath $source) (Join-Path $DistDir $server.pakset.folder) $server.id
        }
    }
    Save-PublishSettings $settings
    if (@($settings.paksets).Count -gt 0) {
        & (Join-Path $PSScriptRoot 'Publish-Pakset.ps1')
    }
    else {
        Write-Warning 'paksetは公開していません。もう一度Setup-Server.batを実行して、paksetフォルダのフルパスを答えてください'
    }
}

# サーバーリストに署名する（鍵がなければここで作る）。友人のランチャーはこの署名で書き換えに気づく
if (Test-Path -LiteralPath $manifestPath) {
    Update-ManifestSignature $manifestPath
}

# --- 5. 確認---
Write-Step '配信できるか確かめています'
foreach ($name in @((Split-Path -Leaf $manifestPath), (Split-Path -Leaf (Get-SignaturePath $manifestPath)))) {
    $localUrl = "http://localhost:$Port/$name"
    try {
        $response = Invoke-WebRequest -Uri $localUrl -UseBasicParsing -TimeoutSec 10
        Write-Ok "$localUrl を取得できました（$($response.RawContentLength)バイト）"
    }
    catch {
        Write-Warning "$localUrl を取得できませんでした: $($_.Exception.Message)"
    }
}
# 書き込み要求（PUT）が断られることを確かめる
try {
    Invoke-WebRequest -Uri "http://localhost:$Port/write-test.txt" -Method Put -Body 'x' -UseBasicParsing -TimeoutSec 10 | Out-Null
    Write-Warning '書き込み要求（PUT）が断られませんでした。IISの「要求フィルター」が入っているか確かめてください'
}
catch {
    $status = $null
    if ($_.Exception.PSObject.Properties['Response'] -and $_.Exception.Response) { $status = [int]$_.Exception.Response.StatusCode }
    if ($status -eq 404 -or $status -eq 405) { Write-Ok "書き込み要求（PUT）は断られました（$status）" }
    else { Write-Warning "書き込み要求（PUT）の確認ができませんでした: $($_.Exception.Message)" }
}
if (Test-Path -LiteralPath (Join-Path $DistDir 'write-test.txt')) {
    Write-Warning '公開フォルダにwrite-test.txtが作られました。書き込みを断る設定が効いていません'
}

# --- 6. HTTPS ---
$https = @(Get-WebBinding -Name $SiteName -Protocol https | Where-Object { ($_.bindingInformation -split ':')[1] -eq "$HttpsPort" }).Count -gt 0
if (-not $https -and -not $SkipHttps) {
    Write-Step 'HTTPSにします（おすすめ。通信を暗号化し、署名に加えてもう一段守ります）'
    $answer = Read-Value "無料の証明書を取ってHTTPS（ポート $HttpsPort）にしますか？80番を開けておく必要があります（Y/n）" 'Y'
    if ($answer -match '^[Yy]') {
        $httpsArgs = @{ HostName = $PublicHost; HttpsPort = $HttpsPort; SiteName = $SiteName; DistDir = $DistDir }
        if ($Email) { $httpsArgs['Email'] = $Email }
        try {
            & (Join-Path $PSScriptRoot 'Enable-Https.ps1') @httpsArgs
            $https = $true
        }
        catch {
            Write-Warning "HTTPSにできませんでした: $($_.Exception.Message)"
            Write-Warning '80番を外から届くようにしてから、Enable-Https.batをダブルクリックしてやり直してください'
        }
    }
}

# ---まとめ---
$hostText = if ($PublicHost) { $PublicHost } else { '<ドメイン>' }
$shareUrl = if ($https) { Get-ShareUrl "https://${hostText}:$HttpsPort" $manifestPath } else { Get-ShareUrl "http://${hostText}:$Port" $manifestPath }
if ($PublicHost -and (Test-Path -LiteralPath $manifestPath)) {
    # サーバー管理ツール（Simutrans_ServerManager.exe）が公開アドレスを表示できるように残す
    $saved = Get-PublishSettings
    $saved.share_url = $shareUrl
    Save-PublishSettings $saved
}
$ports = if ($https) { "TCP 80・$HttpsPort・simutransサーバーのポート" } else { "TCP $Port・simutransサーバーのポート" }
Write-Host ''
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host ' 構築が終わりました。残りの作業:' -ForegroundColor Cyan
Write-Host "  1. 外から $ports に届くようにする（Windowsのファイアウォールはこのツールで開けました）"
Write-Host '     - VPSの場合: 事業者の管理画面のパケットフィルター/セキュリティグループで許可する（その仕組みがなければ不要）'
Write-Host '     - 自宅の場合: ルーターのポート転送でこのサーバーへ転送する'
Write-Host "  2. 自分のPCのブラウザで $shareUrl が開けるか確かめる"
Write-Host "  3. 友人にこのアドレスと確認コードを伝える（DiscordのDMなど）"
Write-Host "     アドレス:   $shareUrl"
$signingKey = Get-SigningKey
if ($signingKey) { Write-Host "     確認コード: $($signingKey.Code)" -ForegroundColor Yellow }
Write-Host '     友人はランチャーの「追加」→「サーバー管理者から共有されたリストを追加」にアドレスを入れ、'
Write-Host '     続けて確認コードを入力する（確認コードは秘密ではない。見せても問題ない）'
Write-Host '  4. 署名の鍵のバックアップを作っていなければ、Manage-SigningKey.batで作ってVPSの外に保管する'
if (-not $https) {
    Write-Host '  ※ HTTPSではありません。署名で書き換えは防げますが、HTTPSにするとより安全です（Enable-Https.batをダブルクリック）'
}
Write-Host '  アドオンを足したあとは: pakをコピー →simutransサーバーを再起動 →Publish-Pakset.batをダブルクリック'
Write-Host '  simutransサーバーを増やすときは: Add-Server.batをダブルクリック'
Write-Host '============================================================' -ForegroundColor Cyan
