<#
.SYNOPSIS
    pakset を Web 公開用フォルダにコピーし、ランチャーの差分同期に使うファイル一覧（index.json）を作る。

.DESCRIPTION
    1. -Source の pakset フォルダの中身を -Destination（Web サーバーで公開しているフォルダ）にコピーする。
       変わったファイルだけをコピーし、-Source から消えたファイルは -Destination からも消す。
    2. -Destination にファイル一覧 index.json（パス・サイズ・SHA256）を書く。
    3. -Destination に IIS 用の web.config を書く（.pak や .tab を配信できるようにするため）。
    4. -Manifest と -ServerId を指定すると、サーバーリストの該当サーバーの pakset を
       index_url / index_sha256 / version に書き換える。同じ pakset を使うサーバーが複数あれば、-ServerId に全部を並べる。

    アドオンを足すときは、-Source の pakset フォルダに pak をコピーしてからこのスクリプトを実行する。
    ランチャーは次に接続するとき、足したファイルだけを落とす。

    -Source と -Destination を省略すると、publish-settings.json に登録されたすべての pakset を公開する
    （Setup-Server.bat / Add-Server.bat が登録する。Publish-Pakset.bat をダブルクリックすると、この形で実行される）。

    Windows PowerShell 5.1 と PowerShell 7 のどちらでも動く。

.EXAMPLE
    .\Publish-Pakset.ps1 -Source C:\simutrans\pak128.japan `
        -Destination C:\inetpub\wwwroot\simutrans\pak128.japan `
        -Manifest C:\inetpub\wwwroot\simutrans\manifest.json -ServerId friends-a
#>
[CmdletBinding()]
param(
    # サーバーが使っている pakset フォルダ（省略すると publish-settings.json の値）
    [string] $Source,
    # Web サーバーで公開するフォルダ（pakset ごとに分ける。省略すると publish-settings.json の値）
    [string] $Destination,
    # 書き換えるサーバーリスト（manifest.json）。省略するとファイル一覧だけ作る
    [string] $Manifest,
    # サーバーリストの中で書き換えるサーバーの id（同じ pakset を使うサーバーが複数あれば、カンマ区切りで並べる）
    [string[]] $ServerId,
    # サーバーリストに書く pakset のバージョン。省略すると日時
    [string] $Version,
    # サーバーリストに書く index.json のアドレス。
    # 省略すると、サーバーリストから見た相対パスにする（-Destination がサーバーリストと同じフォルダかその下にある場合）
    [string] $IndexUrl
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

# ランチャーが受け付けない種類のファイル（InfraLauncher.Core の ManifestClient.BlockedExtensions と同じ）
$BlockedExtensions = @(
    '.exe', '.dll', '.com', '.scr', '.msi', '.msp', '.bat', '.cmd', '.ps1', '.psm1', '.vbs', '.vbe',
    '.js', '.jse', '.wsf', '.wsh', '.hta', '.lnk', '.url', '.reg', '.cpl', '.jar', '.sh', '.app', '.so', '.dylib'
)
$Reserved = @('index.json', 'web.config')
$WebConfigMarker = 'Generated by Publish-Pakset.ps1'
. (Join-Path $PSScriptRoot 'Common.ps1')

function Test-Inside([string] $child, [string] $parent) {
    $sep = [System.IO.Path]::DirectorySeparatorChar
    return $child.StartsWith($parent + $sep, [System.StringComparison]::OrdinalIgnoreCase) -or
        $child.Equals($parent, [System.StringComparison]::OrdinalIgnoreCase)
}

function Get-RelativePath([string] $root, [string] $path) {
    return $path.Substring($root.Length + 1).Replace('\', '/')
}

function Get-Sha256([string] $path) {
    return (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
}


# --- 準備 ---
if (-not $Source -and -not $Destination) {
    # 登録されたすべての pakset を公開する
    $settings = Get-PublishSettings
    if (@($settings.paksets).Count -eq 0) {
        throw "公開する pakset が登録されていません。Setup-Server.bat か Add-Server.bat で登録するか、-Source と -Destination を指定してください"
    }
    foreach ($p in $settings.paksets) {
        Write-Step "$($p.pakset_source) を公開します（サーバー: $($p.server_ids -join ', ')）"
        & $PSCommandPath -Source $p.pakset_source -Destination $p.destination -Manifest $settings.manifest -ServerId $p.server_ids -Version $Version
    }
    return
}
if (-not $Source -or -not $Destination) {
    throw "-Source と -Destination は両方指定してください"
}
$src = Get-FullPath $Source
$dst = Get-FullPath $Destination
if (-not (Test-Path -LiteralPath $src -PathType Container)) {
    throw "pakset フォルダが見つかりません: $src"
}
if ((Test-Inside $dst $src) -or (Test-Inside $src $dst)) {
    throw "-Source と -Destination は、互いの中にない別のフォルダを指定してください"
}
if ($Manifest -and -not $ServerId) {
    throw "-Manifest を指定するときは -ServerId も指定してください"
}
New-Item -ItemType Directory -Force -Path $dst | Out-Null

# --- 1. 公開するファイルを集める ---
$files = @()
foreach ($f in Get-ChildItem -LiteralPath $src -Recurse -File -Force) {
    $rel = Get-RelativePath $src $f.FullName
    if ($BlockedExtensions -contains $f.Extension.ToLowerInvariant()) {
        Write-Warning "実行ファイルなどは公開しません（ランチャーが受け付けないため）: $rel"
        continue
    }
    if ($Reserved -contains $rel.ToLowerInvariant()) {
        throw "pakset フォルダの直下に $rel があります。この名前はファイル一覧用に使うため、名前を変えてください"
    }
    $files += [pscustomobject]@{ Rel = $rel; Source = $f }
}
$files = @($files | Sort-Object -Property Rel -CaseSensitive)
if ($files.Count -eq 0) {
    throw "pakset フォルダにファイルがありません: $src"
}

# --- 2. 変わったファイルだけコピーする ---
$copied = 0
foreach ($f in $files) {
    $target = Join-Path $dst ($f.Rel.Replace('/', [System.IO.Path]::DirectorySeparatorChar))
    $existing = Get-Item -LiteralPath $target -Force -ErrorAction SilentlyContinue
    if ($existing -and $existing.Length -eq $f.Source.Length -and $existing.LastWriteTimeUtc -eq $f.Source.LastWriteTimeUtc) {
        continue
    }
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target) | Out-Null
    Copy-Item -LiteralPath $f.Source.FullName -Destination $target -Force
    (Get-Item -LiteralPath $target -Force).LastWriteTimeUtc = $f.Source.LastWriteTimeUtc
    $copied++
}

# --- 3. ファイル一覧を書く（ファイルをそろえてから書く） ---
$entries = @()
$total = [long]0
foreach ($f in $files) {
    $target = Join-Path $dst ($f.Rel.Replace('/', [System.IO.Path]::DirectorySeparatorChar))
    $entries += [ordered]@{ path = $f.Rel; size = [long]$f.Source.Length; sha256 = (Get-Sha256 $target) }
    $total += $f.Source.Length
}
$indexPath = Join-Path $dst 'index.json'
$indexJson = ConvertTo-Json -InputObject ([ordered]@{ schema_version = 1; files = $entries }) -Depth 5
Write-TextFile $indexPath $indexJson
$indexSha = Get-Sha256 $indexPath

# --- 4. -Source から消えたファイルを片付ける（一覧を書いたあとに消す） ---
$keep = @{}
foreach ($f in $files) { $keep[$f.Rel.ToLowerInvariant()] = $true }
$removed = 0
foreach ($f in Get-ChildItem -LiteralPath $dst -Recurse -File -Force) {
    $rel = (Get-RelativePath $dst $f.FullName).ToLowerInvariant()
    if (-not $keep.ContainsKey($rel) -and -not ($Reserved -contains $rel)) {
        Remove-Item -LiteralPath $f.FullName -Force
        $removed++
    }
}
Get-ChildItem -LiteralPath $dst -Recurse -Directory -Force |
    Sort-Object { $_.FullName.Length } -Descending |
    Where-Object { -not (Get-ChildItem -LiteralPath $_.FullName -Force) } |
    Remove-Item -Force

# --- 5. IIS 用の web.config（既存のものが自作なら触らない） ---
$webConfig = Join-Path $dst 'web.config'
if (-not (Test-Path -LiteralPath $webConfig) -or (Get-Content -LiteralPath $webConfig -Raw).Contains($WebConfigMarker)) {
    $extensions = @($files | ForEach-Object { [System.IO.Path]::GetExtension($_.Rel).ToLowerInvariant() } |
        Where-Object { $_ -and $_ -ne '.json' } | Sort-Object -Unique)
    $maps = ($extensions | ForEach-Object {
        "      <remove fileExtension=`"$_`" />`r`n      <mimeMap fileExtension=`"$_`" mimeType=`"application/octet-stream`" />"
    }) -join "`r`n"
    Write-TextFile $webConfig @"
<?xml version="1.0" encoding="utf-8"?>
<!-- $WebConfigMarker. pakset のファイルを IIS から配信できるようにする。 -->
<configuration>
  <system.webServer>
    <staticContent>
$maps
    </staticContent>
  </system.webServer>
</configuration>
"@
}

# --- 6. サーバーリストを書き換える ---
if ($Manifest) {
    $manifestPath = Get-FullPath $Manifest
    $data = Read-JsonFile $manifestPath
    $targets = @()
    foreach ($id in $ServerId) {
        $found = @($data.servers | Where-Object { $_.id -eq $id })
        if ($found.Count -ne 1) {
            throw "サーバーリストに id が '$id' のサーバーが見つかりません"
        }
        $targets += $found[0]
    }

    if (-not $IndexUrl) {
        $manifestDir = Split-Path -Parent $manifestPath
        if (-not (Test-Inside $indexPath $manifestDir)) {
            throw "-Destination がサーバーリストと同じフォルダの下にないため、相対パスにできません。-IndexUrl で index.json のアドレスを指定してください"
        }
        $IndexUrl = Get-RelativePath $manifestDir $indexPath
    }
    if (-not $Version) {
        $Version = Get-Date -Format 'yyyy.MM.dd-HHmm'
    }

    foreach ($server in $targets) {
        $pakset = $server.pakset
        foreach ($name in @('url', 'sha256')) {
            if ($pakset.PSObject.Properties[$name]) { $pakset.PSObject.Properties.Remove($name) }
        }
        $pakset | Add-Member -NotePropertyName version -NotePropertyValue $Version -Force
        $pakset | Add-Member -NotePropertyName index_url -NotePropertyValue $IndexUrl -Force
        $pakset | Add-Member -NotePropertyName index_sha256 -NotePropertyValue $indexSha -Force
    }
    $data | Add-Member -NotePropertyName updated_at -NotePropertyValue (Get-Date -Format 'yyyy-MM-ddTHH:mm:sszzz') -Force
    Write-JsonFile $manifestPath $data
}

# --- 結果 ---
Write-Host ("公開しました: {0} ファイル（{1:N0} バイト）、コピー {2} 件、削除 {3} 件" -f $files.Count, $total, $copied, $removed)
Write-Host "ファイル一覧: $indexPath"
Write-Host "index_sha256: $indexSha"
if ($Manifest) {
    Write-Host "サーバーリストを更新しました: $manifestPath（$($ServerId -join ', ')、version $Version、index_url $IndexUrl）"
}
